export interface bestiary_ua_2021mos {
  name: string;
  source: string;
  page: number;
  size: string[];
  type: string;
  alignment: string[];
  ac: object[];
  hp: object;
  speed: object;
  str: number;
  dex: number;
  con: number;
  int: number;
  wis: number;
  cha: number;
  save: object;
  skill: object;
  passive: string;
  immune: string[];
  conditionImmune: string[];
  languages: string[];
  pbNote: string;
  trait: object[];
  action: object[];
  reaction: object[];
  miscTags: string[];
  hasToken: boolean;
}
