export interface bestiary_nrh_avitw {
  name: string;
  source: string;
  page: number;
  size: string[];
  type: string;
  alignment: string[];
  ac: number[];
  hp: object;
  speed: object;
  str: number;
  dex: number;
  con: number;
  int: number;
  wis: number;
  cha: number;
  skill?: object;
  senses: string[];
  passive: number;
  cr: string;
  trait: object[];
  action: object[];
  traitTags: string[];
  senseTags: string[];
  damageTags: string[];
  miscTags: string[];
  hasToken: boolean;
  conditionImmune?: string[];
}
